13NetTeam.Web/Models/ErrorViewModel.cs
using System;

namespace _13NetTeam.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

13NetTeam.Web/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _13NetTeam.Core.Contexts;
using _13NetTeam.Core.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _13NetTeam.Web.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly Context _context;

        public CategoriasController(Context context)
        {
            _context = context;
        }



        public async Task<IActionResult> Create(int id)
        {

            var pergunta = await _context.Perguntas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pergunta == null)
            {
                return NotFound();
            }

            ViewBag.Pergunta = pergunta;

            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id_pergunta")] int id_pergunta, [Bind("Autor,Descricao")] Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                var pergunta = _context.Perguntas.Include(p => p.Tags).First(m => m.Id == id_pergunta);
                pergunta.Tags.Add(categoria);
                await _context.SaveChangesAsync();
                return RedirectToAction($"Details//{id_pergunta}", "Perguntas");
            }
            return View(categoria);
        }
    }
}

13NetTeam.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using _13NetTeam.Web.Models;
using _13NetTeam.Core.Contexts;
using Microsoft.EntityFrameworkCore;

namespace _13NetTeam.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly Context _context;

        public HomeController(Context context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            ViewBag.Perguntas = await _context.Perguntas.Include(p => p.Respostas).ToListAsync();

            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

13NetTeam.Web/Controllers/PerguntasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _13NetTeam.Core.Contexts;
using _13NetTeam.Core.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _13NetTeam.Web.Controllers
{
    public class PerguntasController : Controller
    {
        private readonly Context _context;

        public PerguntasController(Context context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
           return View(await _context.Perguntas.Include(p => p.Respostas).ToListAsync());
        }

        public IActionResult Create()
        {
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Autor,Descricao")] Pergunta pergunta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pergunta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pergunta);
        }


        // GET: Perguntas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pergunta = await _context.Perguntas.Include(p => p.Respostas).FirstOrDefaultAsync(m => m.Id == id);
           
            if (pergunta == null)
            {
                return NotFound();
            }
           

            return View(pergunta);
        }

    }
}

13NetTeam.Web/Controllers/RespostasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using _13NetTeam.Core.Contexts;
using _13NetTeam.Core.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace _13NetTeam.Web.Controllers
{
    public class RespostasController : Controller
    {
        private readonly Context _context;

        public RespostasController(Context context)
        {
            _context = context;
        }

        public async Task<IActionResult> Create(int id)
        {
           
            var pergunta = await _context.Perguntas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pergunta == null)
            {
                return NotFound();
            }

            ViewBag.Pergunta = pergunta;

            return View();
        }

        // POST: Perguntas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id_pergunta")] int id_pergunta, [Bind("Autor,Descricao")] Resposta resposta)
        {
            if (ModelState.IsValid)
            {
                var pergunta =  _context.Perguntas.Include(p => p.Respostas).First(m => m.Id == id_pergunta);
                pergunta.Respostas.Add(resposta);
                await _context.SaveChangesAsync();
                return RedirectToAction($"Details//{id_pergunta}","Perguntas");
            }
            return View(resposta);
        }
    }
}

13NetTeam.Web/Views/Categorias/Create.cshtml
@model _13NetTeam.Core.Models.Categoria

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Categoria</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descrição" class="control-label"></label>
                <input asp-for="Descrição" class="form-control" />
                <span asp-validation-for="Descrição" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

13NetTeam.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

13NetTeam.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

13NetTeam.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active" >
            <img src="~/images/banner1.jpg" alt="ASP.NET" class="img-circle center-block" />
            <div class="carousel-caption" role="option">
                <p>
                   13 Net Team Solution
                    
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner1.jpg" alt="ASP.NET" class="img-thumbnail center-block" />
            <div class="carousel-caption" role="option">
                <p>
                    13 Net Team Solution

                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner1.jpg" alt="ASP.NET" class="img-rounded center-block" />
            <div class="carousel-caption" role="option">
                <p>
                    13 Net Team Solution

                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th>
                  Titulo
                </th>
                <th>
                   Autor
                </th>
                <th>
                   Descrição
                </th>
                <th>
                    Respostas
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewBag.Perguntas)
            {
                <tr>
                    <td>
                       @item.Titulo
                    </td>
                    <td>
                        @item.Autor
                    </td>
                    <td>
                        @item.Descricao
                    </td>
                    <td>
                       @item.TotalRespostas()
                    
                    </td>
                    <td>
                        <a asp-controller="Perguntas" asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                        <a asp-controller="Perguntas" asp-action="Details" asp-route-id="@item.Id">Respostas</a> |
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

13NetTeam.Web/Views/Perguntas/Create.cshtml
@model _13NetTeam.Core.Models.Pergunta

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Pergunta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" multiple height="100" maxlength="1000"/>
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

13NetTeam.Web/Views/Perguntas/Details.cshtml
@model _13NetTeam.Core.Models.Pergunta

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pergunta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dd>
            <dl class="dl-horizontal">

                @if (Model.Respostas != null)
                {
                    foreach (var item in Model.Respostas)
                    {
                        <dt>
                            Resposta
                        </dt>
                        <dd>
                            @item.Descricao
                            <br>
                            Autor =  @item.Autor
                        </dd>

                    }
                }
            </dl>
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Respostas" asp-action="Create" asp-route-id="@Model.Id">Responder</a> |
    
    <a asp-action="Index">Voltar</a>
</div>

13NetTeam.Web/Views/Perguntas/Index.cshtml
@model IEnumerable<_13NetTeam.Core.Models.Pergunta>

@{
    ViewData["Title"] = "Index";
}

<h2>Perguntas</h2>

<p>
    <a asp-action="Create">Criar Nova</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th>
                Respostas
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
               @item.TotalRespostas()
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Respostas</a> |
            </td>
        </tr>
}
    </tbody>
</table>

13NetTeam.Web/Views/Respostas/Create.cshtml
@model _13NetTeam.Core.Models.Resposta

@{
    ViewData["Title"] = "Nova Resposta";
}

<h2>@ViewBag.Pergunta.Titulo</h2>

<h4>Resposta</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <input hidden name="id_pergunta" value="@ViewBag.Pergunta.Id" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Perguntas" asp-action="Details" asp-route-id="@ViewBag.Pergunta.Id">Voltar</a> |
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

13NetTeam.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _13NetTeam.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">_13NetTeam.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Perguntas" asp-action="Index">Perguntas</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - _13NetTeam.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>